name = "AlgebraicSolving"
uuid = "66b61cbe-0446-4d5d-9090-1ff510639f9d"
authors = ["ederc <ederc@mathematik.uni-kl.de>",
        "Mohab Safey El Din <Mohab.Safey@lip6.fr"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
msolve_jll = "6d01cc9a-e8f6-580e-8c54-544227e08205"

[compat]
julia = "1.6"
AbstractAlgebra = "0.26.0"
msolve_jll = "0.2.5"
