site_name:           AlgebraicSolving.jl
repo_url:            https://github.com/algebraic-solving/AlgebraicSolving.jl
site_description:    AlgebraicSolving
site_author:         Christian Eder, Mohab Safey El Din

theme:               readthedocs

pages:
- Getting Started:  index.md
- Gröbner bases:    groebner-bases.md

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML']
